### ISSUE TITLE
Feature Request: Track Metadata Output to Text File

### ISSUE THREAD

**Issue by hellnegative** [brunchboy/beat-link-trigger#29]
The track Artist and Title output to be sent to a text file or something similar so that it may be integrated into RADR or other tweeting software.

**Comment by brunchboy** [comment]
This is certainly possible. I showed someone how to collect a performance log in a text file, which is more or less the same thing. No changes are required to Beat Link Trigger to implement this; it can be done by writing an appropriate set of trigger expressions in the user interface. I will leave this open as a reminder to add this example to the user guide, but if you get it figured out before I do that, please share your solution and I will put it in the user guide.

Also, if you have pointers to the documentation of your tweeting software, I may be able to provide a more tailored example of how to integrate to it directly.

**Comment by brunchboy** [comment]
Actually, there is already an [example](https://github.com/brunchboy/beat-link-trigger/blob/master/doc/README.adoc#writing-a-playlist) in the user guide of writing track metadata to a text file. If your browser doesn’t scroll to the proper section when trying to follow that link, search for the heading “Writing a Playlist”.

**Comment by brunchboy** [comment]
@hellnegative can you comment on what is missing from the example from your perspective? Or, if you have succeeded in integrating with your external software, could you share the expression code you used? If I don’t hear anything in a few days I will close this issue as a duplicate.
