### ISSUE TITLE
Rekordbox Dj as Master Player?

### ISSUE THREAD

**Issue by ITSMASAKA** [brunchboy/beat-link-trigger#34]
Im interested if it possible to make Rekordbox Dj the master player?
I like to send the beat info to the djm900 mixer. Right now this is not possible
with pioneer. My setup is 2x Technics SL1200mk2 and 1x DJM900 mixer.
Im playing with Rekordbox on my Macbook, but its not possible to send the correct
info via Pro DJ Link to from the macbook to the Mixer.

Thanks.

**Comment by brunchboy** [comment]
If it doesn’t work with Pioneer gear, it’s not likely to work with Beat Link Trigger; we build on what they provide. However, please try it and see what you can figure out. If you can take network captures and find a way to make it work, the details would be most appreciated!

**Comment by ITSMASAKA** [comment]
for sure it would be possible, because Rekordbox is sending out some info.
But i really have no idea where to start..

**Comment by brunchboy** [comment]
That doesn’t follow… if Rekordbox was sending out the correct information, it would already work with other Pioneer gear. They would not send out the necessary information but in a format that didn’t work with their existing hardware, so it is extremely unlikely that the packets we need are available at all. It’s probable that Rekordbox DJ, much like the DDJ-RX, is simply incapable of being linked like this.

However, if you do want to know where to start, study my [dysentery](https://github.com/brunchboy/dysentery) project, especially the protocol analysis document, where I carefully explain everything that has been learned about how the DJ Link protocol works. Once you thoroughly understand that, you will be able to look at the packets being sent by Rekordbox, and determine exactly what is, and is not, possible.
