### ISSUE TITLE
0.3.8 preview: Fixed BPM not completely fixed

### ISSUE THREAD

**Issue by aftermathematic** [brunchboy/beat-link-trigger#36]
I tested the settings with the fixed BPM to 120 like you instructed on Gitter. 
It does work, but the BPM doesn't stay fixed on 120. It fluctuates during the song between 119.5 and 121, and for the most part of the song it's around 119.6.
If you want I can record it on video so you can see for yourself.

**Comment by brunchboy** [comment]
This is the nature of MIDI clock sync, and that is why I wrote Carabiner. If you want rock-solid sync, use Carabiner and the Link protocol which is designed to work with computers.
