### ISSUE TITLE
can't create Virtual Cdj

### ISSUE THREAD

**Issue by djxandertangel** [brunchboy/beat-link-trigger#39]
I always get this bug - and error says adress is already in use, So I can only chose offline and thats not working. Pls help

**Comment by brunchboy** [comment]
I’m sorry, there’s just not enough information to help you. You will need to figure out what else is using the address, or if you have some firewall software that is preventing BLT from opening it’s port. For example, if you were trying to run BLT on the same computer that rekordbox was already running on, of course this kind of problem would occur because rekordbox is already using the ports needed to implement the DJ Link protocol.

**Comment by djxandertangel** [comment]
No firewall in use mate, but that means that rekordbox should run on one Mac and bt on a second one ?

**Comment by djxandertangel** [comment]
My use case is the following, rekordbox with pro link on 2 cdj 2000 nexus 2 , with Ableton Link enabled to run Soundswitch for the lights (can happen on 2 PCs or just on one if possible)

**Comment by djxandertangel** [comment]
And the test was on one pc

**Comment by brunchboy** [comment]
Yes, it’s impossible to run two different programs that implement DJ Link on the same computer. As it says on the project ReadMe:

> You should also not expect to be able to run Beat Link Trigger, or any project like it, on the same machine that you are running rekordbox, because they will compete over access to network ports.

**Comment by djxandertangel** [comment]
Ok that would mean it’s good to go if rekordbox does only run on the cdjs itself for example with usb plugged in or might it be possible to run it on 2 PCs ?

**Comment by brunchboy** [comment]
You should be fine with USB on the CDJs, or with rekordbox on a separate computer from BLT, yes. People have succeeded using both approaches.

**Comment by djxandertangel** [comment]
ok I got it working with usbs, on the carbiner window it says link bpm 120 , no matter if i turn the fader up or down - and soundswitch also hat 120 in the window, BLT has the right bpm in it - do i do something wrong here ?

**Comment by brunchboy** [comment]
Unfortunately I can’t see exactly what you are doing, so I recommend carefully reviewing the Carabiner section of the BLT user guide. You need to have the Carabiner window open, a successful connection to the Carabiner daemon, and a trigger that is configured to use Carabiner that is enabled and active.

**Comment by djxandertangel** [comment]
mate can u pls provide a link on that usage guide ....
https://github.com/brunchboy/beat-link-trigger i am searching here and there is n carabiner section , in the downloaded bundle neither - so where can i find the missing pieces

**Comment by brunchboy** [comment]
The Going Further section of that page links to it: https://github.com/brunchboy/beat-link-trigger/blob/master/doc/README.adoc#beat-link-trigger-user-guide

**Comment by brunchboy** [comment]
When I get back home I will try to make that more evident. Sorry about the confusion!

**Comment by djxandertangel** [comment]
Thank u for your patience mate, or maybe if u have a tutorial video on how to set it up, guess would help a lot of us

**Comment by djxandertangel** [comment]
finally got it working, thx mate,
