### ISSUE TITLE
Send note on beat

### ISSUE THREAD

**Issue by homer43** [brunchboy/beat-link-trigger#50]
### Version of Beat Link Trigger

0.3.8

### Version of Java

Version 8 Update 181

### Version of OS

Windows 10

### The issue you're experiencing

I didn't success to send a note on each beat to trigger an animation in  SunLite Suite 2

**Comment by brunchboy** [comment]
This doesn’t sound like an issue with the software, but like you are having questions about how to use and integrate it. Please ask those in the [Gitter chat room](
https://gitter.im/brunchboy/beat-link-trigger) and hopefully someone will be able to help you. Be prepared to give very specific details about what you are trying to do, how you have tried to do it, and what you are observing. I’m not sure if any other users have worked with SunLite Suite, so you may need to explain how that works too. Have you tried using a tool like Midi Monitor to see if you are sending the Midi you expect?

**Comment by brunchboy** [comment]
(Midi Monitor is a Mac tool, but I expect there is something similar available for Windows; it shows you all MIDI activity on the system, and lets you filter it to focus on what you are trying to see.)

**Comment by homer43** [comment]
Thanks you, but I didn't success to write a script to send a midi note on each beat.

**Comment by brunchboy** [comment]
I understand that. I am trying to explain how you might be able to find people to help you do that. Share exactly what you did, and what you expected to happen, and what actually happened, on the Gitter chat channel that I linked to above. What was your script? What was showing in the Player Status window while the track was playing? What appeared in the log file?

If someone has time to volunteer to help you, they will need full details to do so. Of course, there is no guarantee that anyone will have the time, but the more details you can offer, the easier you make it for someone to help you, and the more likely you will get useful help.

**Comment by homer43** [comment]
Ok thank you 
!!
